import Link from "next/link";

const capabilities = [
  { icon: "▦", title: "Room operations", description: "See availability, housekeeping, arrivals, and date-specific room rates in one place." },
  { icon: "♙", title: "Guest relationships", description: "Keep booking history close and make it easier to welcome returning guests." },
  { icon: "♧", title: "Restaurant service", description: "Manage your menu and record restaurant sales with a simple point of sale." },
  { icon: "¤", title: "Clearer finances", description: "Track recorded expenses, room payments, and sales reports for each property." },
  { icon: "✳", title: "Innova AI", description: "Ask an operations assistant for ideas using your property's aggregate figures." },
  { icon: "⌂", title: "One or more properties", description: "Switch between property workspaces while keeping each property's records separate." },
];

export default function HomePage() {
  return <main className="landing-page">
    <header className="landing-header"><Link className="brand landing-brand" href="/"><span className="brand-mark">i</span><span>innova<span className="brand-ai">.ai</span></span></Link><nav aria-label="Main navigation"><a href="#platform">Platform</a><a href="#how-it-works">How it works</a><Link href="/login">Sign in</Link><Link className="primary-button" href="/signup">Create an account <span>→</span></Link></nav></header>
    <section className="landing-hero"><div className="landing-hero-copy"><p className="eyebrow"><span /> BUILT FOR HOSPITALITY TEAMS</p><h1>Less switching.<br /><em>More welcoming.</em></h1><p className="landing-lede">Run rooms, reservations, restaurant sales, and daily operations from one clear workspace—built for the people who make hospitality happen.</p><div className="landing-actions"><Link className="primary-button" href="/signup">Get started <span>→</span></Link><Link className="landing-secondary-link" href="/login">I already have an account</Link></div><p className="landing-hero-footnote">Start by creating a property workspace. Add your rooms and team when you’re ready.</p></div><div className="landing-visual" aria-label="Illustration of a property operations dashboard"><div className="landing-visual-top"><span><i /> Innova overview</span><small>Today</small></div><div className="landing-visual-welcome"><small>YOUR PROPERTY, AT A GLANCE</small><strong>Good morning.</strong><span>Your team is ready for today.</span></div><div className="landing-visual-stats"><div><small>ROOMS OCCUPIED</small><strong>•••</strong><i>Guest stays</i></div><div><small>UPCOMING ARRIVALS</small><strong>••</strong><i>Reservations</i></div></div><div className="landing-visual-bookings"><div><strong>Today&apos;s operations</strong><small>Room and restaurant tools</small></div><span className="landing-visual-leaf">✳</span></div><div className="landing-visual-bars"><i /><i /><i /><i /><i /><i /><i /></div><div className="landing-visual-caption">One workspace. A clearer day.</div></div></section>
    <section className="landing-trust-row"><span>ROOMS &amp; RESERVATIONS</span><i /><span>RESTAURANT &amp; POS</span><i /><span>FINANCE &amp; REPORTS</span><i /><span>TEAM OPERATIONS</span></section>
    <section className="landing-platform" id="platform"><div className="landing-section-heading"><p className="eyebrow">THE INNOVA WORKSPACE</p><h2>Hospitality runs on many details.<br /><em>Keep them connected.</em></h2><p>Give your team one place for the work behind a good guest experience, from the first booking to the end-of-day review.</p></div><div className="landing-capabilities">{capabilities.map((item) => <article className="landing-capability" key={item.title}><span>{item.icon}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
    <section className="landing-how" id="how-it-works"><div><p className="eyebrow">A PRACTICAL START</p><h2>Set up your property.<br /><em>Then grow into the rest.</em></h2><p>Innova starts with the daily tools your team needs. Add rooms, configure your menu, record expenses, and invite teammates as your workflow takes shape.</p><Link className="text-action" href="/signup">Create your workspace →</Link></div><div className="landing-steps"><article><span>01</span><div><strong>Create your workspace</strong><small>Add your property name, location, timezone, and currency.</small></div></article><article><span>02</span><div><strong>Add your operations</strong><small>Set up rooms, rates, reservations, menu items, and team roles.</small></div></article><article><span>03</span><div><strong>Run the day</strong><small>Review arrivals, record sales and payments, and ask Innova AI for guidance.</small></div></article></div></section>
    <section className="landing-final-cta"><div><p className="eyebrow">INNOVA AI</p><h2>Make space for the<br /><em>hospitality part.</em></h2><p>Bring the moving pieces of your property into one calm, clear workspace.</p></div><Link className="primary-button" href="/signup">Create an account <span>→</span></Link></section>
    <footer className="landing-footer"><Link className="brand landing-brand" href="/"><span className="brand-mark">i</span><span>innova<span className="brand-ai">.ai</span></span></Link><span>Hospitality, in harmony.</span><div><Link href="/login">Sign in</Link><Link href="/signup">Get started</Link></div></footer>
  </main>;
}
