-- Add a simple, hotel-scoped POS sale ledger with atomic sale creation.

create table if not exists public.pos_orders (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references public.hotels (id) on delete cascade,
  order_number bigint generated by default as identity,
  payment_method text not null check (payment_method in ('cash', 'card', 'mobile_money')),
  total_amount numeric(12, 2) not null default 0 check (total_amount >= 0),
  created_by uuid not null references auth.users (id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (hotel_id, id),
  unique (hotel_id, order_number)
);

create table if not exists public.pos_order_items (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null,
  order_id uuid not null,
  menu_item_id uuid not null,
  item_name text not null check (char_length(btrim(item_name)) between 2 and 120),
  quantity smallint not null check (quantity between 1 and 100),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now(),
  foreign key (hotel_id, order_id)
    references public.pos_orders (hotel_id, id) on delete cascade
);

create index if not exists pos_orders_hotel_created_idx
  on public.pos_orders (hotel_id, created_at desc);
create index if not exists pos_order_items_hotel_order_idx
  on public.pos_order_items (hotel_id, order_id);

alter table public.pos_orders enable row level security;
alter table public.pos_order_items enable row level security;

drop policy if exists "Hotel members can view POS orders" on public.pos_orders;
create policy "Hotel members can view POS orders"
  on public.pos_orders for select to authenticated
  using ((select private.has_hotel_role(hotel_id, array['owner', 'admin', 'manager', 'staff'])));

drop policy if exists "Hotel members can view POS order items" on public.pos_order_items;
create policy "Hotel members can view POS order items"
  on public.pos_order_items for select to authenticated
  using ((select private.has_hotel_role(hotel_id, array['owner', 'admin', 'manager', 'staff'])));

revoke all on public.pos_orders from anon, authenticated;
grant select on public.pos_orders to authenticated;
revoke all on public.pos_order_items from anon, authenticated;
grant select on public.pos_order_items to authenticated;

create or replace function public.create_pos_sale(
  p_hotel_id uuid,
  p_lines jsonb,
  p_payment_method text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_order_number bigint;
  v_line jsonb;
  v_item_id uuid;
  v_quantity integer;
  v_item_name text;
  v_unit_price numeric(12, 2);
  v_line_total numeric(12, 2);
  v_total numeric(12, 2) := 0;
  v_line_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Sign in is required' using errcode = '42501';
  end if;
  if not private.has_hotel_role(p_hotel_id, array['owner', 'admin', 'manager', 'staff']) then
    raise exception 'Not allowed to record a sale for this hotel' using errcode = '42501';
  end if;
  if p_payment_method not in ('cash', 'card', 'mobile_money') then
    raise exception 'Invalid payment method' using errcode = '22023';
  end if;
  if p_lines is null or pg_catalog.jsonb_typeof(p_lines) <> 'array'
     or pg_catalog.jsonb_array_length(p_lines) < 1
     or pg_catalog.jsonb_array_length(p_lines) > 50 then
    raise exception 'A sale must contain between 1 and 50 items' using errcode = '22023';
  end if;

  insert into public.pos_orders (hotel_id, payment_method, total_amount, created_by)
  values (p_hotel_id, p_payment_method, 0, auth.uid())
  returning id, order_number into v_order_id, v_order_number;

  for v_line in select value from pg_catalog.jsonb_array_elements(p_lines)
  loop
    begin
      v_item_id := (v_line ->> 'menu_item_id')::uuid;
      v_quantity := (v_line ->> 'quantity')::integer;
    exception when others then
      raise exception 'Invalid menu item or quantity' using errcode = '22023';
    end;

    if v_quantity < 1 or v_quantity > 100 then
      raise exception 'Quantity must be between 1 and 100' using errcode = '22023';
    end if;

    select item.name, item.price
      into v_item_name, v_unit_price
      from public.menu_items as item
      where item.id = v_item_id
        and item.hotel_id = p_hotel_id
        and item.is_available = true;

    if not found then
      raise exception 'A menu item is missing or unavailable' using errcode = '22023';
    end if;

    v_line_total := round(v_unit_price * v_quantity, 2);
    insert into public.pos_order_items (
      hotel_id, order_id, menu_item_id, item_name, quantity, unit_price, line_total
    ) values (
      p_hotel_id, v_order_id, v_item_id, v_item_name, v_quantity,
      v_unit_price, v_line_total
    );
    v_total := v_total + v_line_total;
    v_line_count := v_line_count + 1;
  end loop;

  update public.pos_orders set total_amount = v_total where id = v_order_id;

  return pg_catalog.jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'total_amount', v_total,
    'line_count', v_line_count
  );
end;
$$;

revoke all on function public.create_pos_sale(uuid, jsonb, text) from public, anon;
grant execute on function public.create_pos_sale(uuid, jsonb, text) to authenticated;
